# MongoDB Atlas Connection String

MONGO_URI = "mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@YOUR_CLUSTER.mongodb.net/?retryWrites=true&w=majority"

DATABASE_NAME = "wifi_db"

COLLECTION_NAME = "wifi_sessions"
